### ISSUE TITLE
It doesn't initialize after compiling

### ISSUE THREAD

**Issue by grunch** [arcbtc/Quickening#2]
Hi, I'm trying to run the quickening but I'm just getting the same white screen since I plugged the nodeMCU.

I changed the variables to make it connect to my lnd node which is in my local network.

I let you know which vars I changed in case you have an idea of what is happening.
wifiSSID: with my ssid
wifiPASS: with my passwd
lndport: I add here my lnd rest port which is open only for my local network
readmacaroon: xxd -plain readonly.macaroon
invoicemacaroon: xxd -plain invoice.macaroon
uncommented `TLSCert.h` and add in that file my `.lnd/tls.cert` file
uncommented lines 279, 303, 360, 403

I don't get any error to lead me to the problem, this is the log from arduino ide
```
esptool.py v2.6
Serial port /dev/ttyUSB0
Connecting........__
Chip is ESP32D0WDQ6 (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
MAC: 24:6f:28:16:ae:84
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 921600
Changed.
Configuring flash size...
Auto-detected Flash size: 4MB
Compressed 8192 bytes to 47...

Writing at 0x0000e000... (100 %)
Wrote 8192 bytes (47 compressed) at 0x0000e000 in 0.0 seconds (effective 31766.8 kbit/s)...
Hash of data verified.
Compressed 15856 bytes to 10276...

Writing at 0x00001000... (100 %)
Wrote 15856 bytes (10276 compressed) at 0x00001000 in 0.1 seconds (effective 1061.5 kbit/s)...
Hash of data verified.
Compressed 902496 bytes to 510615...

Writing at 0x00010000... (3 %)
Writing at 0x00014000... (6 %)
Writing at 0x00018000... (9 %)
Writing at 0x0001c000... (12 %)
Writing at 0x00020000... (15 %)
Writing at 0x00024000... (18 %)
Writing at 0x00028000... (21 %)
Writing at 0x0002c000... (25 %)
Writing at 0x00030000... (28 %)
Writing at 0x00034000... (31 %)
Writing at 0x00038000... (34 %)
Writing at 0x0003c000... (37 %)
Writing at 0x00040000... (40 %)
Writing at 0x00044000... (43 %)
Writing at 0x00048000... (46 %)
Writing at 0x0004c000... (50 %)
Writing at 0x00050000... (53 %)
Writing at 0x00054000... (56 %)
Writing at 0x00058000... (59 %)
Writing at 0x0005c000... (62 %)
Writing at 0x00060000... (65 %)
Writing at 0x00064000... (68 %)
Writing at 0x00068000... (71 %)
Writing at 0x0006c000... (75 %)
Writing at 0x00070000... (78 %)
Writing at 0x00074000... (81 %)
Writing at 0x00078000... (84 %)
Writing at 0x0007c000... (87 %)
Writing at 0x00080000... (90 %)
Writing at 0x00084000... (93 %)
Writing at 0x00088000... (96 %)
Writing at 0x0008c000... (100 %)
Wrote 902496 bytes (510615 compressed) at 0x00010000 in 7.7 seconds (effective 934.1 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 128...

Writing at 0x00008000... (100 %)
Wrote 3072 bytes (128 compressed) at 0x00008000 in 0.0 seconds (effective 7637.2 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
```

**Comment by Yamto** [comment]
I have the same problem. My TFT just displays a white screen. As I understand from the serial monitor the code is working fine.

I know the hardware works fine since I had it working from bitbrum.

Did you find a fix?

**Comment by grunch** [comment]
not at all, I don't know how to debug with arduino ide

**Comment by arcbtc** [comment]
Hey guys. Sorry for the late reply. Have you been into the library folder and changed the driver for TFT_eSPI?
Open user_setup.h 

![TFT_eSPI](https://i.imgur.com/OnWrkBQ.png)

Uncomment `#define ST7735_DRIVER`

![TFT_eSPI](https://i.imgur.com/OABjKJ9.png)

**Comment by arcbtc** [comment]
If you don't assign the correct driver you'll get a white screen

To test you could run one of the example programs in file>examples>TFT_eSPI

Also, make sure you have "ESP32 Dev Module" selected for your board

**Comment by grunch** [comment]
Hi, thank you for your response.

I uncommented the line `#define ST7735_DRIVER` and now I get a new error and the screen keeps showing white.

I was using ESP32 NODEMCU-32S, but now I tried with ESP32 Dev Module but still doesn't work, also I tried with an example of the TFT_eSPI module, and the same thing happens, here the log.
```
home/grunch/arduino/hardware/espressif/esp32/cores/esp32/esp32-hal-spi.c: In function 'spiTransferBytes':
/home/grunch/arduino/hardware/espressif/esp32/cores/esp32/esp32-hal-spi.c:682:37: warning: passing argument 2 of '__spiTransferBytes' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
             __spiTransferBytes(spi, data, out, 64);
                                     ^
/home/grunch/arduino/hardware/espressif/esp32/cores/esp32/esp32-hal-spi.c:633:6: note: expected 'uint8_t * {aka unsigned char *}' but argument is of type 'const uint8_t * {aka const unsigned char *}'
 void __spiTransferBytes(spi_t * spi, uint8_t * data, uint8_t * out, uint32_t bytes)
      ^
/home/grunch/arduino/hardware/espressif/esp32/cores/esp32/esp32-hal-spi.c:691:37: warning: passing argument 2 of '__spiTransferBytes' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
             __spiTransferBytes(spi, data, out, size);
                                     ^
/home/grunch/arduino/hardware/espressif/esp32/cores/esp32/esp32-hal-spi.c:633:6: note: expected 'uint8_t * {aka unsigned char *}' but argument is of type 'const uint8_t * {aka const unsigned char *}'
 void __spiTransferBytes(spi_t * spi, uint8_t * data, uint8_t * out, uint32_t bytes)
      ^
El Sketch usa 902662 bytes (68%) del espacio de almacenamiento de programa. El máximo es 1310720 bytes.
Las variables Globales usan 40520 bytes (12%) de la memoria dinámica, dejando 287160 bytes para las variables locales. El máximo es 327680 bytes.
esptool.py v2.6
Serial port /dev/ttyUSB0
Connecting........_____....._____..
Chip is ESP32D0WDQ6 (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
MAC: 24:6f:28:16:ae:84
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 921600
Changed.
Configuring flash size...
Auto-detected Flash size: 4MB
Compressed 8192 bytes to 47...

Writing at 0x0000e000... (100 %)
Wrote 8192 bytes (47 compressed) at 0x0000e000 in 0.0 seconds (effective 25498.9 kbit/s)...
Hash of data verified.
Compressed 17392 bytes to 11186...

Writing at 0x00001000... (100 %)
Wrote 17392 bytes (11186 compressed) at 0x00001000 in 0.1 seconds (effective 929.5 kbit/s)...
Hash of data verified.
Compressed 902784 bytes to 510925...

Writing at 0x00010000... (3 %)
Writing at 0x00014000... (6 %)
Writing at 0x00018000... (9 %)
Writing at 0x0001c000... (12 %)
Writing at 0x00020000... (15 %)
Writing at 0x00024000... (18 %)
Writing at 0x00028000... (21 %)
Writing at 0x0002c000... (25 %)
Writing at 0x00030000... (28 %)
Writing at 0x00034000... (31 %)
Writing at 0x00038000... (34 %)
Writing at 0x0003c000... (37 %)
Writing at 0x00040000... (40 %)
Writing at 0x00044000... (43 %)
Writing at 0x00048000... (46 %)
Writing at 0x0004c000... (50 %)
Writing at 0x00050000... (53 %)
Writing at 0x00054000... (56 %)
Writing at 0x00058000... (59 %)
Writing at 0x0005c000... (62 %)
Writing at 0x00060000... (65 %)
Writing at 0x00064000... (68 %)
Writing at 0x00068000... (71 %)
Writing at 0x0006c000... (75 %)
Writing at 0x00070000... (78 %)
Writing at 0x00074000... (81 %)
Writing at 0x00078000... (84 %)
Writing at 0x0007c000... (87 %)
Writing at 0x00080000... (90 %)
Writing at 0x00084000... (93 %)
Writing at 0x00088000... (96 %)
Writing at 0x0008c000... (100 %)
Wrote 902784 bytes (510925 compressed) at 0x00010000 in 7.8 seconds (effective 929.1 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 128...

Writing at 0x00008000... (100 %)
Wrote 3072 bytes (128 compressed) at 0x00008000 in 0.0 seconds (effective 6498.1 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
```

**Comment by Yamto** [comment]
> If you don't assign the correct driver you'll get a white screen
> 
> To test you could run one of the example programs in file>examples>TFT_eSPI
> 
> Also, make sure you have "ESP32 Dev Module" selected for your board

Could you please give me a copy of your user_setup.h file because I can't get this to work. It just displays a white screen.

**Comment by arcbtc** [comment]
[TFT_eSPI.zip](https://github.com/arcbtc/Quickening/files/3863567/TFT_eSPI.zip)

**Comment by arcbtc** [comment]
That's the whole library. Wiring or library would be the first thing I check with a white screen. One of the first commands is to blackout the screen

**Comment by Yamto** [comment]
> [TFT_eSPI.zip](https://github.com/arcbtc/Quickening/files/3863567/TFT_eSPI.zip)

Thanks, that worked the first time. Must be a different version to the current one.

**Comment by arcbtc** [comment]
Weird, maybe I changed a different parameter somewhere else. I'll cross-reference with library later

**Comment by arcbtc** [comment]
So is it fully operational?

**Comment by arcbtc** [comment]
Changed the code.

![image](https://user-images.githubusercontent.com/33088785/69146671-3d83b480-0ac8-11ea-9767-d155c71d2195.png)

Use PoS Integrations
Go to Integrations on the left to get your API key

**Comment by arcbtc** [comment]
Add the paywall id to the new arduino code 
![image](https://user-images.githubusercontent.com/33088785/69146845-97847a00-0ac8-11ea-8a39-5c09795e7f19.png)
![image](https://user-images.githubusercontent.com/33088785/69146878-a834f000-0ac8-11ea-9967-0b42c1035ebc.png)

**Comment by arcbtc** [comment]
This way you could have multiple POS terminals all feeding into the same account

**Comment by Yamto** [comment]
> So is it fully operational?

Yeah, I've just implemented the paywall method.

**Comment by arcbtc** [comment]
Saweeet! Congrats

**Comment by grunch** [comment]
Hi, this original issue is not about using paywall, I still have the issue with the quickening :disappointed:
